#Dragon Curve Fractal
"""
    Grab a stip of paper (longer is better), mark one side of it as being "up".

    fold it in the middle, while always keeping the up side markng facing the same direction. That's the first iteration.
    Holding it on the same way, Fold it on the middle again. That's the second iteration.
    fold it again. That's the third iteration.
    Notice that, when the strip is unfold, the pattern of "in" and "out" (valleys[V] and mountais[M]) foldings isn't that predictable.
    Fold it as much as you like/can.

    To visalize the fractal, unfold it at every iteration, and try to align each folding on a 90° angle.
    At each iteration, the size of the present curve is reduced by a factor of 1/2. And the previous shape is duplicated, but with a 90° degree angle.
    All the curve can be viewed as being generated by duplicating and rotating itself.
"""
#Now the Sequence
iterations = 14
Sequence = ['V']
def invert(array):
    inverted = []
    for i in array:
        if i == 'V':
            inverted.append('M')
        elif i == 'M':
            inverted.append('V')
    inverted.reverse() #Reverses an array
    return inverted 
##Just Playing
mode = 1
if mode == 1:#Default Up folding
    for i in range(iterations):
        Sequence += ['V'] + invert(Sequence)
    print(Sequence)
    print(len(Sequence))
elif mode == 2:#Down and Up Folding
    for i in range(iterations):
        if i % 2 == 0:
            Sequence += ['M'] + invert(Sequence)
        if i % 2 == 1:
            Sequence += ['V'] + invert(Sequence)
    print(Sequence)
    print(len(Sequence))
elif mode == 3:#1 Down and 2 Up foldings
    for i in range(iterations):
        if i % 3 == 0:
            Sequence += ['M'] + invert(Sequence)
        else:
            Sequence += ['V'] + invert(Sequence)
    print(Sequence)
    print(len(Sequence))
elif mode == 4:#4 Up and 4 Down Foldings
    for i in range(iterations):
        if i % 4 == 0:
            Sequence += ['V'] + invert(Sequence)
        else:
            Sequence += ['M'] + invert(Sequence)
    print(Sequence)
    print(len(Sequence))
    
#Now the turtle
import turtle
wn = turtle.Screen()#
wn.tracer(0) #rurn off window updates

dragon = turtle.Turtle()
#dragon.speed(iterations*2)
dragon.speed(0)
for i in Sequence:
    if i == 'V':
        dragon.left(90)
    else:
        dragon.right(90)
    dragon.forward(100//(iterations*6))
wn.update()#

wn.mainloop()#
turtle.done()