from math import log
#Dragon Curve Fractal

#How it works
"""
    Grab a stip of paper (longer is better), mark one side of it as being "up".

    fold it in the middle, while always keeping the marked side always facing up. That's the first iteration.
    Holding it on the same way, Fold it on the middle again. That's the second iteration.
    fold it again. That's the third iteration.
    Notice that, when the strip is unfold, the pattern of "in" and "out" (valleys[V] and mountais[M]) foldings isn't that predictable.
    Fold it as much as you like/can.

    To visalize the fractal, unfold it at every iteration, and try to ali8gn each folding as a 90° angle.
    At each iteration, the size of the present curve is reduced by a factor of 1/2. And the previous shape is duplicated, but with a 90° degree angle.
    All the curve can be viewed as being generated by duplicating and rotating itself (rotating is represented by the invert() function) as shown in other animations out there.
    
    This code was inspired by a great Numberphile video about it.
"""
#Now the Sequence
iterations = int(input("Iterations: "))
Sequence = ['V']
def invert(array):
    inverted = []
    for i in array:
        if i == 'V':
            inverted.append('M')
        elif i == 'M':
            inverted.append('V')
    inverted.reverse() #Reverses an array
    return inverted 

##Now the folding
for i in range(iterations):
    Sequence += ['V'] + invert(Sequence)
    print(Sequence)
    print(len(Sequence))

#Now the turtle
import turtle
wn = turtle.Screen()
wn.tracer(0) #0 to turn off window updates

dragon = turtle.Turtle()
#dragon.speed(iterations*2)
dragon.speed(0)
for i in Sequence:
    if i == 'V':
        dragon.left(90)
    else:
        dragon.right(90)
    dragon.forward(100//(iterations * 4)) # For appropriate scaling
wn.update()#

wn.mainloop()#
turtle.done()